build:
  image: node:20-alpine
  tags:
    - docker
  script:
    - cd frontend && npm install && npm run build
    - cd ../backend && npm install
  artifacts:
    paths:
      - frontend/dist/ # will save the build files, to check how well it works, might remove later