build:
  image: docker:latest
  tags:
    - docker
  services:
    - docker:dind # Docker inside Docker , should work
  before_script:
    - apk add --no-cache docker-compose # actually install docker-compose
  script:
    - docker compose up --build -d
    - sleep 10                          # wait for stuff to fully start up
    - docker compose ps                 # debug stuff
    - docker compose logs
    - curl -f http://localhost:3000 || echo "Frontend check failed"
    - docker-compose down